ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MODERATOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN';
CREATE TYPE "ConsentScope" AS ENUM ('AI_PROCESSING', 'VOICE_PROCESSING', 'DEVICE_EMOTION_OBSERVATION', 'HEATMAP_CONTRIBUTION');
CREATE TYPE "ConsentStatus" AS ENUM ('ACCEPTED', 'REVOKED');
CREATE TYPE "AccessibilityTextScale" AS ENUM ('SMALL', 'STANDARD', 'LARGE', 'EXTRA_LARGE');
CREATE TYPE "CommunityTargetType" AS ENUM ('POST', 'COMMENT');
CREATE TYPE "CommunityReportReason" AS ENUM ('HARASSMENT', 'SELF_HARM', 'SPAM', 'MISINFORMATION', 'PRIVACY', 'OTHER');
CREATE TYPE "CommunityReportStatus" AS ENUM ('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED');
CREATE TYPE "ModerationAction" AS ENUM ('HIDE', 'RESTORE', 'RESOLVE_REPORT', 'DISMISS_REPORT');
CREATE TYPE "MindfulnessType" AS ENUM ('BREATHING', 'MEDITATION', 'GROUNDING');
CREATE TYPE "MindfulnessProgressStatus" AS ENUM ('STARTED', 'COMPLETED');
CREATE TYPE "ProviderType" AS ENUM ('PSYCHOLOGIST', 'COUNSELOR', 'CRISIS_LINE', 'CLINIC');
CREATE TYPE "DeviceCommandType" AS ENUM ('HAPTIC_THERAPY', 'DISPLAY_MESSAGE', 'SET_CONFIGURATION', 'RESTART');
CREATE TYPE "DeviceCommandStatus" AS ENUM ('PENDING', 'ACKNOWLEDGED', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE "EmotionObservationSource" AS ENUM ('VOICE', 'CAMERA', 'FUSED');
CREATE TYPE "DeviceCheckInKind" AS ENUM ('MOOD', 'CHECK_IN');
CREATE TYPE "FirmwareStatus" AS ENUM ('ACTIVE', 'DEPRECATED');
CREATE TYPE "OtaStatus" AS ENUM ('PENDING', 'DOWNLOADING', 'INSTALLING', 'SUCCEEDED', 'FAILED', 'CANCELLED');

ALTER TABLE "CommunityComment" ADD COLUMN "isHidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserPreference" ADD COLUMN "textScale" "AccessibilityTextScale" NOT NULL DEFAULT 'STANDARD', ADD COLUMN "highContrast" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "reducedMotion" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "screenReaderOptimized" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PsychologistApplication" ADD COLUMN "reviewedById" TEXT;
ALTER TABLE "Device" ADD COLUMN "unpairedAt" TIMESTAMP(3), ADD COLUMN "revokedAt" TIMESTAMP(3), ADD COLUMN "lastSeenAt" TIMESTAMP(3), ADD COLUMN "firmwareVersion" TEXT, ADD COLUMN "hardwareRevision" TEXT, ADD COLUMN "bootloaderVersion" TEXT, ADD COLUMN "protocolVersion" TEXT, ADD COLUMN "supportedCommandTypes" "DeviceCommandType"[] NOT NULL DEFAULT ARRAY[]::"DeviceCommandType"[];
ALTER TABLE "VoiceTurn" ADD COLUMN "idempotencyKey" TEXT, ADD COLUMN "language" TEXT NOT NULL DEFAULT 'id', ADD COLUMN "transcript" TEXT, ADD COLUMN "responseText" TEXT, ADD COLUMN "riskLevel" "RiskLevel", ADD COLUMN "upstreamRequestId" TEXT, ADD COLUMN "referralId" TEXT;
ALTER TABLE "VoiceTurn" ALTER COLUMN "language" DROP DEFAULT;

CREATE TABLE "ConsentDocument" ("id" TEXT NOT NULL, "scope" "ConsentScope" NOT NULL, "version" INTEGER NOT NULL, "title" TEXT NOT NULL, "content" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "effectiveAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ConsentDocument_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserConsent" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "documentId" TEXT NOT NULL, "scope" "ConsentScope" NOT NULL, "version" INTEGER NOT NULL, "status" "ConsentStatus" NOT NULL, "acceptedAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "source" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UserConsent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HeatmapContribution" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "regionKey" TEXT NOT NULL, "mood" "MoodState" NOT NULL, "bucketDate" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HeatmapContribution_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CommunityReport" ("id" TEXT NOT NULL, "reporterId" TEXT NOT NULL, "targetType" "CommunityTargetType" NOT NULL, "targetId" TEXT NOT NULL, "postId" TEXT, "commentId" TEXT, "reason" "CommunityReportReason" NOT NULL, "details" TEXT, "status" "CommunityReportStatus" NOT NULL DEFAULT 'OPEN', "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CommunityReport_pkey" PRIMARY KEY ("id"), CONSTRAINT "CommunityReport_target_check" CHECK (("targetType" = 'POST' AND "postId" IS NOT NULL AND "commentId" IS NULL) OR ("targetType" = 'COMMENT' AND "commentId" IS NOT NULL AND "postId" IS NULL)));
CREATE TABLE "CommunityModerationAudit" ("id" TEXT NOT NULL, "moderatorId" TEXT NOT NULL, "action" "ModerationAction" NOT NULL, "targetType" "CommunityTargetType" NOT NULL, "targetId" TEXT NOT NULL, "reportId" TEXT, "reason" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CommunityModerationAudit_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DailyMotivation" ("id" TEXT NOT NULL, "date" DATE NOT NULL, "locale" TEXT NOT NULL, "message" TEXT NOT NULL, "author" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DailyMotivation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MindfulnessActivity" ("id" TEXT NOT NULL, "slug" TEXT NOT NULL, "type" "MindfulnessType" NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "durationSeconds" INTEGER NOT NULL, "locale" TEXT NOT NULL, "steps" TEXT[], "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MindfulnessActivity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MindfulnessProgress" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "activityId" TEXT NOT NULL, "status" "MindfulnessProgressStatus" NOT NULL DEFAULT 'STARTED', "progressSeconds" INTEGER NOT NULL DEFAULT 0, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MindfulnessProgress_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmergencyContact" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "name" TEXT NOT NULL, "relationship" TEXT NOT NULL, "phone" TEXT NOT NULL, "isPrimary" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "EmergencyContact_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Provider" ("id" TEXT NOT NULL, "slug" TEXT NOT NULL, "name" TEXT NOT NULL, "type" "ProviderType" NOT NULL, "description" TEXT NOT NULL, "phone" TEXT, "websiteUrl" TEXT, "address" TEXT, "region" TEXT NOT NULL, "languages" TEXT[], "isEmergency" BOOLEAN NOT NULL DEFAULT false, "isVerified" BOOLEAN NOT NULL DEFAULT false, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Provider_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceCredential" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "tokenDigest" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "lastUsedAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DeviceCredential_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceTelemetry" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "metric" TEXT NOT NULL, "value" DOUBLE PRECISION NOT NULL, "unit" TEXT, "recordedAt" TIMESTAMP(3) NOT NULL, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "metadata" JSONB, CONSTRAINT "DeviceTelemetry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceEmotionObservation" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "userId" TEXT NOT NULL, "source" "EmotionObservationSource" NOT NULL, "inputSources" "EmotionObservationSource"[] NOT NULL DEFAULT ARRAY[]::"EmotionObservationSource"[], "state" "MoodState" NOT NULL, "confidence" DOUBLE PRECISION NOT NULL, "riskLevel" "RiskLevel" NOT NULL, "facePresent" BOOLEAN, "eyeContact" BOOLEAN, "expressionProbabilities" JSONB, "observationProvider" TEXT NOT NULL, "modelName" TEXT NOT NULL, "modelVersion" TEXT NOT NULL, "consentId" TEXT NOT NULL, "consentVersion" INTEGER NOT NULL, "retentionPolicy" TEXT NOT NULL, "retainUntil" TIMESTAMP(3) NOT NULL, "idempotencyKey" TEXT NOT NULL, "observedAt" TIMESTAMP(3) NOT NULL, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DeviceEmotionObservation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceCheckIn" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "userId" TEXT NOT NULL, "moodId" TEXT NOT NULL, "kind" "DeviceCheckInKind" NOT NULL, "idempotencyKey" TEXT NOT NULL, "observedAt" TIMESTAMP(3) NOT NULL, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DeviceCheckIn_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceCommand" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "type" "DeviceCommandType" NOT NULL, "payload" JSONB NOT NULL, "status" "DeviceCommandStatus" NOT NULL DEFAULT 'PENDING', "idempotencyKey" TEXT, "acknowledgedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "errorCode" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DeviceCommand_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FirmwareRelease" ("id" TEXT NOT NULL, "model" TEXT NOT NULL, "version" TEXT NOT NULL, "hardwareRevision" TEXT, "minimumBootloaderVersion" TEXT, "protocolVersion" TEXT NOT NULL, "downloadUrl" TEXT NOT NULL, "checksumSha256" TEXT NOT NULL, "releaseNotes" TEXT, "status" "FirmwareStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FirmwareRelease_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DeviceOtaDeployment" ("id" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "firmwareId" TEXT NOT NULL, "status" "OtaStatus" NOT NULL DEFAULT 'PENDING', "progress" INTEGER NOT NULL DEFAULT 0, "errorCode" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DeviceOtaDeployment_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "ConsentDocument_scope_version_key" ON "ConsentDocument"("scope", "version");
CREATE INDEX "ConsentDocument_scope_isActive_effectiveAt_idx" ON "ConsentDocument"("scope", "isActive", "effectiveAt");
CREATE UNIQUE INDEX "UserConsent_userId_documentId_key" ON "UserConsent"("userId", "documentId");
CREATE INDEX "UserConsent_userId_scope_status_updatedAt_idx" ON "UserConsent"("userId", "scope", "status", "updatedAt");
CREATE INDEX "UserConsent_documentId_idx" ON "UserConsent"("documentId");
CREATE UNIQUE INDEX "HeatmapContribution_userId_bucketDate_key" ON "HeatmapContribution"("userId", "bucketDate");
CREATE INDEX "HeatmapContribution_regionKey_bucketDate_mood_idx" ON "HeatmapContribution"("regionKey", "bucketDate", "mood");
CREATE INDEX "CommunityComment_isHidden_createdAt_idx" ON "CommunityComment"("isHidden", "createdAt");
CREATE UNIQUE INDEX "CommunityReport_reporterId_targetType_targetId_key" ON "CommunityReport"("reporterId", "targetType", "targetId");
CREATE INDEX "CommunityReport_status_createdAt_idx" ON "CommunityReport"("status", "createdAt");
CREATE INDEX "CommunityReport_postId_idx" ON "CommunityReport"("postId");
CREATE INDEX "CommunityReport_commentId_idx" ON "CommunityReport"("commentId");
CREATE INDEX "CommunityModerationAudit_moderatorId_createdAt_idx" ON "CommunityModerationAudit"("moderatorId", "createdAt");
CREATE INDEX "CommunityModerationAudit_target_idx" ON "CommunityModerationAudit"("targetType", "targetId", "createdAt");
CREATE INDEX "CommunityModerationAudit_reportId_idx" ON "CommunityModerationAudit"("reportId");
CREATE UNIQUE INDEX "DailyMotivation_date_locale_key" ON "DailyMotivation"("date", "locale");
CREATE INDEX "DailyMotivation_locale_date_idx" ON "DailyMotivation"("locale", "date");
CREATE UNIQUE INDEX "MindfulnessActivity_slug_key" ON "MindfulnessActivity"("slug");
CREATE INDEX "MindfulnessActivity_locale_isPublished_type_idx" ON "MindfulnessActivity"("locale", "isPublished", "type");
CREATE UNIQUE INDEX "MindfulnessProgress_userId_activityId_key" ON "MindfulnessProgress"("userId", "activityId");
CREATE INDEX "MindfulnessProgress_userId_updatedAt_idx" ON "MindfulnessProgress"("userId", "updatedAt");
CREATE INDEX "EmergencyContact_userId_isPrimary_createdAt_idx" ON "EmergencyContact"("userId", "isPrimary", "createdAt");
CREATE UNIQUE INDEX "Provider_slug_key" ON "Provider"("slug");
CREATE INDEX "Provider_region_isActive_type_idx" ON "Provider"("region", "isActive", "type");
CREATE INDEX "Provider_isEmergency_isActive_idx" ON "Provider"("isEmergency", "isActive");
CREATE UNIQUE INDEX "DeviceCredential_tokenDigest_key" ON "DeviceCredential"("tokenDigest");
CREATE INDEX "DeviceCredential_deviceId_revokedAt_expiresAt_idx" ON "DeviceCredential"("deviceId", "revokedAt", "expiresAt");
CREATE INDEX "DeviceTelemetry_deviceId_recordedAt_idx" ON "DeviceTelemetry"("deviceId", "recordedAt");
CREATE INDEX "DeviceTelemetry_metric_recordedAt_idx" ON "DeviceTelemetry"("metric", "recordedAt");
CREATE UNIQUE INDEX "DeviceEmotionObservation_deviceId_idempotencyKey_key" ON "DeviceEmotionObservation"("deviceId", "idempotencyKey");
CREATE INDEX "DeviceEmotionObservation_deviceId_observedAt_idx" ON "DeviceEmotionObservation"("deviceId", "observedAt");
CREATE INDEX "DeviceEmotionObservation_userId_observedAt_idx" ON "DeviceEmotionObservation"("userId", "observedAt");
CREATE INDEX "DeviceEmotionObservation_retainUntil_idx" ON "DeviceEmotionObservation"("retainUntil");
CREATE UNIQUE INDEX "DeviceCheckIn_moodId_key" ON "DeviceCheckIn"("moodId");
CREATE UNIQUE INDEX "DeviceCheckIn_deviceId_idempotencyKey_key" ON "DeviceCheckIn"("deviceId", "idempotencyKey");
CREATE INDEX "DeviceCheckIn_userId_observedAt_idx" ON "DeviceCheckIn"("userId", "observedAt");
CREATE UNIQUE INDEX "DeviceCommand_deviceId_idempotencyKey_key" ON "DeviceCommand"("deviceId", "idempotencyKey");
CREATE INDEX "DeviceCommand_deviceId_status_createdAt_idx" ON "DeviceCommand"("deviceId", "status", "createdAt");
CREATE UNIQUE INDEX "FirmwareRelease_model_version_key" ON "FirmwareRelease"("model", "version");
CREATE INDEX "FirmwareRelease_model_status_createdAt_idx" ON "FirmwareRelease"("model", "status", "createdAt");
CREATE INDEX "DeviceOtaDeployment_deviceId_status_createdAt_idx" ON "DeviceOtaDeployment"("deviceId", "status", "createdAt");
CREATE INDEX "DeviceOtaDeployment_firmwareId_idx" ON "DeviceOtaDeployment"("firmwareId");
CREATE UNIQUE INDEX "VoiceTurn_userId_idempotencyKey_key" ON "VoiceTurn"("userId", "idempotencyKey");
CREATE UNIQUE INDEX "VoiceTurn_referralId_key" ON "VoiceTurn"("referralId");
CREATE INDEX "VoiceTurn_riskLevel_createdAt_idx" ON "VoiceTurn"("riskLevel", "createdAt");
CREATE INDEX "PsychologistApplication_reviewedById_reviewedAt_idx" ON "PsychologistApplication"("reviewedById", "reviewedAt");

UPDATE "CommunityComment" SET "userId" = NULL WHERE "userId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "User" WHERE "User"."id" = "CommunityComment"."userId");
ALTER TABLE "CommunityComment" ADD CONSTRAINT "CommunityComment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PsychologistApplication" ADD CONSTRAINT "PsychologistApplication_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UserConsent" ADD CONSTRAINT "UserConsent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserConsent" ADD CONSTRAINT "UserConsent_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "ConsentDocument"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "HeatmapContribution" ADD CONSTRAINT "HeatmapContribution_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CommunityReport" ADD CONSTRAINT "CommunityReport_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CommunityReport" ADD CONSTRAINT "CommunityReport_postId_fkey" FOREIGN KEY ("postId") REFERENCES "CommunityPost"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CommunityReport" ADD CONSTRAINT "CommunityReport_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "CommunityComment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CommunityModerationAudit" ADD CONSTRAINT "CommunityModerationAudit_moderatorId_fkey" FOREIGN KEY ("moderatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MindfulnessProgress" ADD CONSTRAINT "MindfulnessProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MindfulnessProgress" ADD CONSTRAINT "MindfulnessProgress_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "MindfulnessActivity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmergencyContact" ADD CONSTRAINT "EmergencyContact_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceCredential" ADD CONSTRAINT "DeviceCredential_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceTelemetry" ADD CONSTRAINT "DeviceTelemetry_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceEmotionObservation" ADD CONSTRAINT "DeviceEmotionObservation_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceEmotionObservation" ADD CONSTRAINT "DeviceEmotionObservation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceEmotionObservation" ADD CONSTRAINT "DeviceEmotionObservation_consentId_fkey" FOREIGN KEY ("consentId") REFERENCES "UserConsent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DeviceCheckIn" ADD CONSTRAINT "DeviceCheckIn_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceCheckIn" ADD CONSTRAINT "DeviceCheckIn_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceCheckIn" ADD CONSTRAINT "DeviceCheckIn_moodId_fkey" FOREIGN KEY ("moodId") REFERENCES "Mood"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceCommand" ADD CONSTRAINT "DeviceCommand_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceOtaDeployment" ADD CONSTRAINT "DeviceOtaDeployment_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "Device"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DeviceOtaDeployment" ADD CONSTRAINT "DeviceOtaDeployment_firmwareId_fkey" FOREIGN KEY ("firmwareId") REFERENCES "FirmwareRelease"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "VoiceTurn" ADD CONSTRAINT "VoiceTurn_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "Referral"("id") ON DELETE SET NULL ON UPDATE CASCADE;
