type Schema = Record<string, unknown>;
type Operation = Record<string, unknown>;
type PathItem = Record<string, Operation>;

const bearerAuth = [{ BearerAuth: [] }];
const deviceAuth = [{ DeviceAuth: [] }];
const cuidParameter = (name: string, description: string) => ({ name, in: 'path', required: true, description, schema: { type: 'string', pattern: '^[a-z0-9]+$' } });
const queryParameter = (name: string, description: string, schema: Schema) => ({ name, in: 'query', required: false, description, schema });
const json = (schema: Schema) => ({ 'application/json': { schema } });
const request = (schema: Schema, required = true) => ({ required, content: json(schema) });
const response = (description: string, schema: Schema = { $ref: '#/components/schemas/SuccessEnvelope' }) => ({ description, content: json(schema) });
const errors = {
  '400': response('Invalid request.', { $ref: '#/components/schemas/ErrorEnvelope' }),
  '401': response('Authentication is required or invalid.', { $ref: '#/components/schemas/ErrorEnvelope' }),
  '403': response('The authenticated principal is not authorized.', { $ref: '#/components/schemas/ErrorEnvelope' }),
  '404': response('The requested resource was not found.', { $ref: '#/components/schemas/ErrorEnvelope' }),
  '409': response('The request conflicts with the current resource state.', { $ref: '#/components/schemas/ErrorEnvelope' }),
  '500': response('Unexpected server error.', { $ref: '#/components/schemas/ErrorEnvelope' }),
};
const authenticated = (tag: string, summary: string, description: string, extra: Operation = {}): Operation => ({ tags: [tag], summary, description: `${description} Requires BearerAuth.`, security: bearerAuth, responses: { '200': response('Success.'), ...errors }, ...extra });
const deviceRuntime = (summary: string, description: string, extra: Operation = {}): Operation => ({ tags: ['Device runtime'], summary, description: `${description} Requires DeviceAuth issued to the paired hardware device.`, security: deviceAuth, responses: { '200': response('Success.'), ...errors }, ...extra });

const id = cuidParameter('id', 'Resource identifier.');
const turnId = cuidParameter('turnId', 'Voice turn identifier.');
const sessionId = cuidParameter('sessionId', 'Care chat session identifier.');
const binaryAudio = {
  required: true,
  content: Object.fromEntries(['audio/wav', 'audio/x-wav', 'audio/mpeg', 'audio/mp4', 'audio/webm', 'audio/ogg'].map((contentType) => [contentType, { schema: { type: 'string', format: 'binary' } }])),
};

export const openapiDocument: Record<string, unknown> = {
  openapi: '3.0.3',
  info: { title: 'Happify Backend API', version: '1.0.0', description: 'Express API for Happify clients and Companion devices. All JSON success responses use `{ status: "success", data?: ... }`; errors use `{ status: "error", message: string }`.' },
  tags: [
    { name: 'Health' }, { name: 'Authentication' }, { name: 'Profile' }, { name: 'Preferences' }, { name: 'Mood' }, { name: 'Journal' }, { name: 'Voice' }, { name: 'Analytics' }, { name: 'Motivation' }, { name: 'Mindfulness' }, { name: 'Community' }, { name: 'Devices' }, { name: 'Device runtime' }, { name: 'Heatmap' }, { name: 'Consents' }, { name: 'Referrals' }, { name: 'Providers' }, { name: 'Emergency contacts' }, { name: 'Notifications' }, { name: 'Media' }, { name: 'Simulator' },
  ],
  paths: {
    '/health': { get: { tags: ['Health'], summary: 'Health check', responses: { '200': response('Service is healthy.', { type: 'object', required: ['status', 'service'], properties: { status: { type: 'string', example: 'healthy' }, service: { type: 'string', example: 'BE-Happify' } } }) } } },
    '/auth/verify': { post: { tags: ['Authentication'], summary: 'Verify Firebase identity token', description: 'Verifies the Bearer token supplied by the client and returns the public user profile.', security: bearerAuth, responses: { '200': response('Verified user.'), ...errors } } },
    '/analytics/dashboard': { get: authenticated('Analytics', 'Get mood dashboard', 'Returns analytics for the current user.') } },
    '/consents': { get: authenticated('Consents', 'List consents', 'Lists the current user consent records.', { parameters: [queryParameter('scope', 'Optionally filter by consent scope.', { type: 'string' })] }), put: authenticated('Consents', 'Update consent', 'Creates or updates a current user consent choice.', { requestBody: request({ $ref: '#/components/schemas/ConsentInput' }) }) },
    '/emergency-contacts': { get: authenticated('Emergency contacts', 'List emergency contacts', 'Lists the current user contacts.'), post: authenticated('Emergency contacts', 'Create emergency contact', 'Creates a contact for the current user.', { requestBody: request({ $ref: '#/components/schemas/EmergencyContactInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/emergency-contacts/{id}': { patch: authenticated('Emergency contacts', 'Update emergency contact', 'Updates a contact owned by the current user.', { parameters: [id], requestBody: request({ $ref: '#/components/schemas/EmergencyContactInput' }) }), delete: authenticated('Emergency contacts', 'Delete emergency contact', 'Deletes a contact owned by the current user.', { parameters: [id], responses: { '204': { description: 'Deleted.' }, ...errors } }) },
    '/community': { get: authenticated('Community', 'List community posts', 'Lists posts visible to the current user.', { parameters: [queryParameter('cursor', 'Pagination cursor.', { type: 'string' }), queryParameter('limit', 'Maximum items.', { type: 'integer', minimum: 1, maximum: 100 })] }), post: authenticated('Community', 'Create community post', 'Creates a post as the current user.', { requestBody: request({ $ref: '#/components/schemas/CommunityPostInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/community/{id}/comments': { post: authenticated('Community', 'Comment on post', 'Adds a comment as the current user.', { parameters: [id], requestBody: request({ type: 'object', required: ['content'], properties: { content: { type: 'string', maxLength: 5000 } } }), responses: { '201': response('Created.'), ...errors } }) },
    '/community/{id}/support': { post: authenticated('Community', 'Support a post', 'Records current user support for a post.', { parameters: [id] }) },
    '/community/reports': { post: authenticated('Community', 'Report community content', 'Reports a post or comment for moderation.', { requestBody: request({ $ref: '#/components/schemas/CommunityReportInput' }), responses: { '201': response('Created.'), ...errors } }), get: authenticated('Community', 'List community reports', 'Role constraint: MODERATOR or ADMIN only.', { parameters: [queryParameter('cursor', 'Pagination cursor.', { type: 'string' }), queryParameter('limit', 'Maximum items.', { type: 'integer', minimum: 1, maximum: 100 })] }) },
    '/community/moderation': { post: authenticated('Community', 'Moderate community content', 'Role constraint: MODERATOR or ADMIN only.', { requestBody: request({ $ref: '#/components/schemas/ModerationInput' }) }) },
    '/devices/runtime/telemetry': { post: deviceRuntime('Ingest telemetry batch', 'Accepts metrics from the authenticated device.', { requestBody: request({ $ref: '#/components/schemas/TelemetryBatchInput' }), responses: { '202': response('Accepted.'), ...errors } }) },
    '/devices/runtime/heartbeat': { post: deviceRuntime('Record heartbeat', 'Updates runtime hardware and firmware status.', { requestBody: request({ $ref: '#/components/schemas/HeartbeatInput' }), responses: { '202': response('Accepted.'), ...errors } }) },
    '/devices/runtime/emotion-observations': { post: deviceRuntime('Ingest emotion observation', 'Accepts extracted observations only; raw images are neither accepted nor stored.', { requestBody: request({ $ref: '#/components/schemas/EmotionObservationInput' }), responses: { '202': response('Accepted.'), ...errors } }) },
    '/devices/runtime/camera-observations': { post: deviceRuntime('Ingest camera observation', 'Accepts derived camera observations only; raw images are neither accepted nor stored.', { requestBody: request({ $ref: '#/components/schemas/CameraObservationInput' }), responses: { '202': response('Accepted.'), ...errors } }) },
    '/devices/runtime/mood-sync': { post: deviceRuntime('Synchronize mood check-in', 'Ingests a device-created mood or check-in record.', { requestBody: request({ $ref: '#/components/schemas/MoodSyncInput' }), responses: { '202': response('Accepted.'), ...errors } }) },
    '/devices/runtime/commands': { get: deviceRuntime('List pending commands', 'Returns commands pending for the authenticated device.') },
    '/devices/runtime/commands/{id}': { patch: deviceRuntime('Update command status', 'Acknowledges, completes, or fails a command for the authenticated device.', { parameters: [id], requestBody: request({ $ref: '#/components/schemas/CommandStatusInput' }) }) },
    '/devices/runtime/ota': { get: deviceRuntime('Get pending OTA deployment', 'Returns the pending deployment for the authenticated device.') },
    '/devices/runtime/ota/{id}': { patch: deviceRuntime('Update OTA deployment', 'Reports OTA progress for the authenticated device.', { parameters: [id], requestBody: request({ $ref: '#/components/schemas/OtaStatusInput' }) }) },
    '/devices': { get: authenticated('Devices', 'List paired devices', 'Lists devices owned by the current user.') },
    '/devices/pairing-sessions': { post: authenticated('Devices', 'Start pairing session', 'Starts a pairing session for a device serial number.', { requestBody: request({ $ref: '#/components/schemas/PairingInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/devices/pairing-sessions/{id}': { get: authenticated('Devices', 'Get pairing session', 'Returns a pairing session owned by the current user.', { parameters: [id] }), delete: authenticated('Devices', 'Cancel pairing session', 'Cancels a pairing session owned by the current user.', { parameters: [id], responses: { '204': { description: 'Cancelled.' }, ...errors } }) },
    '/devices/pairing-sessions/{id}/complete': { post: authenticated('Devices', 'Complete pairing session', 'Pairs the device to the current user.', { parameters: [id] }) },
    '/devices/firmware': { post: authenticated('Devices', 'Create firmware release', 'Role constraint: ADMIN only.', { requestBody: request({ $ref: '#/components/schemas/FirmwareInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/devices/firmware/{id}/status': { patch: authenticated('Devices', 'Update firmware status', 'Role constraint: ADMIN only.', { parameters: [id], requestBody: request({ type: 'object', required: ['status'], properties: { status: { type: 'string', enum: ['ACTIVE', 'DEPRECATED'] } } }) }) },
    '/devices/{id}': { get: authenticated('Devices', 'Get device', 'Returns a device owned by the current user.', { parameters: [id] }), patch: authenticated('Devices', 'Rename device', 'Updates the display name of a device owned by the current user.', { parameters: [id], requestBody: request({ type: 'object', required: ['displayName'], properties: { displayName: { type: 'string', maxLength: 60 } } }) }), delete: authenticated('Devices', 'Unpair device', 'Unpairs a device owned by the current user.', { parameters: [id], requestBody: request({ type: 'object', properties: { revoke: { type: 'boolean', default: false } } }) }) },
    '/devices/{id}/credentials': { post: authenticated('Devices', 'Issue device credential', 'Issues a runtime credential for a device owned by the current user. The credential is returned only by this operation.', { parameters: [id], responses: { '201': response('Created.'), ...errors } }) },
    '/devices/{id}/telemetry': { get: authenticated('Devices', 'List device telemetry', 'Lists telemetry for a device owned by the current user.', { parameters: [id, queryParameter('limit', 'Maximum items; 1 to 500.', { type: 'integer', minimum: 1, maximum: 500, default: 100 })] }) },
    '/devices/{id}/firmware-releases': { get: authenticated('Devices', 'List compatible firmware releases', 'Lists releases compatible with a device owned by the current user.', { parameters: [id] }) },
    '/devices/{id}/commands': { post: authenticated('Devices', 'Create device command', 'Queues a command for a device owned by the current user.', { parameters: [id], requestBody: request({ $ref: '#/components/schemas/DeviceCommandInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/devices/{id}/ota': { post: authenticated('Devices', 'Create OTA deployment', 'Queues a firmware deployment for a device owned by the current user.', { parameters: [id], requestBody: request({ type: 'object', required: ['firmwareId'], properties: { firmwareId: { type: 'string' } } }), responses: { '201': response('Created.'), ...errors } }) },
    '/heatmap': { get: authenticated('Heatmap', 'List anonymous mood heatmap', 'Returns k-anonymous aggregate heatmap data for the current user.') },
    '/heatmap/contribution': { put: authenticated('Heatmap', 'Update heatmap contribution', 'Creates or updates the current user anonymous contribution.', { requestBody: request({ $ref: '#/components/schemas/HeatmapContributionInput' }) }) },
    '/journal': { get: authenticated('Journal', 'List journal entries', 'Lists the current user journal entries.', { parameters: [queryParameter('cursor', 'Pagination cursor.', { type: 'string' }), queryParameter('limit', 'Maximum items.', { type: 'integer', minimum: 1, maximum: 100 })] }), post: authenticated('Journal', 'Create journal entry', 'Creates a journal entry for the current user.', { requestBody: request({ $ref: '#/components/schemas/JournalInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/media/images': { post: authenticated('Media', 'Upload image', 'Uploads a JSON-described image payload for the current user.', { requestBody: request({ $ref: '#/components/schemas/ImageUploadInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/media/images/{key}': { get: authenticated('Media', 'Retrieve image', 'Returns an image only when its storage key belongs to the current user.', { parameters: [cuidParameter('key', 'URL-encoded storage key.')], responses: { '200': { description: 'Image bytes.', content: { 'image/*': { schema: { type: 'string', format: 'binary' } } } }, ...errors } }) },
    '/mindfulness': { get: authenticated('Mindfulness', 'List mindfulness content', 'Lists content and progress for the current user.', { parameters: [queryParameter('locale', 'Content locale.', { type: 'string' }), queryParameter('type', 'Content type.', { type: 'string' })] }) },
    '/mindfulness/progress': { put: authenticated('Mindfulness', 'Update mindfulness progress', 'Updates current user progress.', { requestBody: request({ $ref: '#/components/schemas/MindfulnessProgressInput' }) }) },
    '/mood': { get: authenticated('Mood', 'List mood records', 'Lists mood records for the current user.'), post: authenticated('Mood', 'Create mood record', 'Creates a mood record for the current user.', { requestBody: request({ $ref: '#/components/schemas/MoodInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/motivation/today': { get: authenticated('Motivation', 'Get daily motivation', 'Returns personalized daily motivation.', { parameters: [queryParameter('locale', 'Content locale.', { type: 'string' })] }) },
    '/notifications/tokens': { put: authenticated('Notifications', 'Register push token', 'Registers or updates a current user push token.', { requestBody: request({ $ref: '#/components/schemas/NotificationTokenInput' }) }), delete: authenticated('Notifications', 'Remove push token', 'Removes a current user push token.', { requestBody: request({ $ref: '#/components/schemas/NotificationTokenInput' }), responses: { '204': { description: 'Removed.' }, ...errors } }) },
    '/preferences': { get: authenticated('Preferences', 'Get preferences', 'Returns preferences for the current user.'), put: authenticated('Preferences', 'Upsert preferences', 'Creates or updates preferences for the current user.', { requestBody: request({ type: 'object', additionalProperties: true }) }) },
    '/profile': { get: authenticated('Profile', 'Get profile', 'Returns the current user public profile.'), patch: authenticated('Profile', 'Update profile', 'Updates the current user public profile.', { requestBody: request({ $ref: '#/components/schemas/ProfileInput' }) }) },
    '/profile/psychologist-applications': { post: authenticated('Profile', 'Apply as psychologist', 'Creates an application for the current user.', { requestBody: request({ $ref: '#/components/schemas/PsychologistApplicationInput' }), responses: { '201': response('Created.'), ...errors } }), get: authenticated('Profile', 'List psychologist applications', 'Role constraint: ADMIN only.') },
    '/profile/psychologist-applications/{id}/review': { patch: authenticated('Profile', 'Review psychologist application', 'Role constraint: ADMIN only.', { parameters: [id], requestBody: request({ type: 'object', required: ['status'], properties: { status: { type: 'string' }, reviewNote: { type: 'string' } } }) }) },
    '/providers': { get: authenticated('Providers', 'List providers', 'Lists provider directory entries.', { parameters: [queryParameter('type', 'Provider type.', { type: 'string' }), queryParameter('query', 'Search query.', { type: 'string' })] }), post: authenticated('Providers', 'Create provider', 'Role constraint: ADMIN only.', { requestBody: request({ $ref: '#/components/schemas/ProviderInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/providers/{id}': { patch: authenticated('Providers', 'Update provider', 'Role constraint: ADMIN only.', { parameters: [id], requestBody: request({ $ref: '#/components/schemas/ProviderInput' }) }) },
    '/referral': { get: authenticated('Referrals', 'List referrals', 'Lists referrals visible to the current user.'), post: authenticated('Referrals', 'Create referral', 'Creates a referral for the current user.', { requestBody: request({ $ref: '#/components/schemas/ReferralInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/referral/chats': { get: authenticated('Referrals', 'List care chats', 'Lists care chats visible to the current user.') },
    '/referral/chats/{sessionId}': { get: authenticated('Referrals', 'Get care chat', 'Returns a care chat visible to the current user.', { parameters: [sessionId] }) },
    '/referral/chats/{sessionId}/status': { patch: authenticated('Referrals', 'Update care chat status', 'Updates a care chat visible to the current user.', { parameters: [sessionId], requestBody: request({ type: 'object', required: ['status'], properties: { status: { type: 'string' } } }) }) },
    '/referral/chats/{sessionId}/messages': { post: authenticated('Referrals', 'Send care chat message', 'Creates a message in a care chat visible to the current user.', { parameters: [sessionId], requestBody: request({ type: 'object', required: ['content'], properties: { content: { type: 'string', maxLength: 10000 } } }), responses: { '201': response('Created.'), ...errors } }) },
    '/referral/{id}/review': { patch: authenticated('Referrals', 'Review referral', 'Role constraint: PSYCHOLOGIST or ADMIN only.', { parameters: [id], requestBody: request({ type: 'object', required: ['status'], properties: { status: { type: 'string' }, note: { type: 'string' } } }) }) },
    '/voice/turns': { get: authenticated('Voice', 'List voice turns', 'Lists voice turns for the current user.'), post: authenticated('Voice', 'Process voice turn', 'Uploads binary audio for transcription and companion processing. Accepted media types: WAV, MPEG, MP4, WebM, and OGG.', { requestBody: binaryAudio, responses: { '201': response('Processed.'), ...errors } }) },
    '/voice/turns/{turnId}/audio': { get: authenticated('Voice', 'Get voice response audio', 'Streams generated response audio for a voice turn owned by the current user.', { parameters: [turnId], responses: { '200': { description: 'Audio bytes.', content: { 'audio/mpeg': { schema: { type: 'string', format: 'binary' } } } }, ...errors } }) },
    '/simulator/devices': { post: authenticated('Simulator', 'Register simulator device', 'Optional route: registered only when ENABLE_SIMULATOR_ROUTES=true. Role constraint: ADMIN only.', { requestBody: request({ $ref: '#/components/schemas/SimulatorDeviceInput' }), responses: { '201': response('Created.'), ...errors } }) },
    '/simulator/firmware': { post: authenticated('Simulator', 'Create simulator firmware', 'Optional route: registered only when ENABLE_SIMULATOR_ROUTES=true. Role constraint: ADMIN only.', { requestBody: request({ $ref: '#/components/schemas/FirmwareInput' }), responses: { '201': response('Created.'), ...errors } }) },
  },
  components: {
    securitySchemes: { BearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'Firebase ID token' }, DeviceAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'Device runtime credential' } },
    schemas: {
      SuccessEnvelope: { type: 'object', required: ['status'], properties: { status: { type: 'string', enum: ['success'] }, data: { type: 'object', additionalProperties: true } } },
      ErrorEnvelope: { type: 'object', required: ['status', 'message'], properties: { status: { type: 'string', enum: ['error'] }, message: { type: 'string' } } },
      ConsentInput: { type: 'object', required: ['scope', 'granted'], properties: { scope: { type: 'string' }, granted: { type: 'boolean' }, version: { type: 'integer', minimum: 1 } }, additionalProperties: false },
      EmergencyContactInput: { type: 'object', required: ['name', 'phoneNumber'], properties: { name: { type: 'string' }, phoneNumber: { type: 'string' }, relationship: { type: 'string' } }, additionalProperties: false },
      CommunityPostInput: { type: 'object', required: ['content'], properties: { content: { type: 'string', maxLength: 5000 }, isAnonymous: { type: 'boolean' } }, additionalProperties: false },
      CommunityReportInput: { type: 'object', required: ['targetType', 'targetId', 'reason'], properties: { targetType: { type: 'string', enum: ['POST', 'COMMENT'] }, targetId: { type: 'string' }, reason: { type: 'string' } }, additionalProperties: false },
      ModerationInput: { type: 'object', required: ['targetType', 'targetId', 'action'], properties: { targetType: { type: 'string' }, targetId: { type: 'string' }, action: { type: 'string' }, reason: { type: 'string' } }, additionalProperties: false },
      PairingInput: { type: 'object', required: ['serialNumber', 'claimSecret'], properties: { serialNumber: { type: 'string', pattern: '^[A-Z0-9-]+$' }, claimSecret: { type: 'string', minLength: 16, writeOnly: true } }, additionalProperties: false },
      TelemetryBatchInput: { type: 'object', required: ['items'], properties: { items: { type: 'array', minItems: 1, maxItems: 100, items: { type: 'object', required: ['metric', 'value', 'recordedAt'], properties: { metric: { type: 'string' }, value: { type: 'number' }, unit: { type: 'string' }, recordedAt: { type: 'string', format: 'date-time' }, metadata: { type: 'object', additionalProperties: { nullable: true } } }, additionalProperties: false } } }, additionalProperties: false },
      HeartbeatInput: { type: 'object', required: ['firmwareVersion', 'hardwareRevision', 'bootloaderVersion', 'protocolVersion', 'supportedCommandTypes'], properties: { firmwareVersion: { type: 'string' }, hardwareRevision: { type: 'string' }, bootloaderVersion: { type: 'string' }, protocolVersion: { type: 'string' }, supportedCommandTypes: { type: 'array', items: { type: 'string', enum: ['HAPTIC_THERAPY', 'DISPLAY_MESSAGE', 'SET_CONFIGURATION', 'RESTART'] } } }, additionalProperties: false },
      EmotionObservationInput: { type: 'object', required: ['source', 'state', 'confidence', 'riskLevel', 'observationProvider', 'consentEvidence', 'retention', 'idempotencyKey', 'observedAt'], properties: { source: { type: 'string', enum: ['VOICE', 'CAMERA', 'FUSED'] }, state: { type: 'string' }, confidence: { type: 'number', minimum: 0, maximum: 1 }, riskLevel: { type: 'string' }, observationProvider: { type: 'object', additionalProperties: { type: 'string' } }, consentEvidence: { type: 'object', properties: { consentId: { type: 'string' }, version: { type: 'integer' } } }, retention: { type: 'object', properties: { policy: { type: 'string' }, retainUntil: { type: 'string', format: 'date-time' } } }, idempotencyKey: { type: 'string' }, observedAt: { type: 'string', format: 'date-time' } }, additionalProperties: false },
      CameraObservationInput: { allOf: [{ $ref: '#/components/schemas/EmotionObservationInput' }, { type: 'object', required: ['facePresent', 'eyeContact', 'expressionProbabilities'], properties: { source: { type: 'string', enum: ['CAMERA'] }, facePresent: { type: 'boolean' }, eyeContact: { type: 'boolean' }, expressionProbabilities: { type: 'object', additionalProperties: { type: 'number', minimum: 0, maximum: 1 } } } }] },
      MoodSyncInput: { type: 'object', required: ['kind', 'state', 'observedAt', 'idempotencyKey'], properties: { kind: { type: 'string', enum: ['MOOD', 'CHECK_IN'] }, state: { type: 'string' }, intensity: { type: 'integer', minimum: 1, maximum: 5 }, triggers: { type: 'array', items: { type: 'string' } }, note: { type: 'string' }, observedAt: { type: 'string', format: 'date-time' }, idempotencyKey: { type: 'string' } }, additionalProperties: false },
      CommandStatusInput: { type: 'object', required: ['status'], properties: { status: { type: 'string', enum: ['ACKNOWLEDGED', 'COMPLETED', 'FAILED'] }, errorCode: { type: 'string' } }, additionalProperties: false },
      OtaStatusInput: { type: 'object', required: ['status', 'progress'], properties: { status: { type: 'string', enum: ['DOWNLOADING', 'INSTALLING', 'SUCCEEDED', 'FAILED'] }, progress: { type: 'integer', minimum: 0, maximum: 100 }, errorCode: { type: 'string' } }, additionalProperties: false },
      FirmwareInput: { type: 'object', required: ['model', 'version', 'protocolVersion', 'downloadUrl', 'checksumSha256'], properties: { model: { type: 'string' }, version: { type: 'string' }, hardwareRevision: { type: 'string' }, minimumBootloaderVersion: { type: 'string' }, protocolVersion: { type: 'string' }, downloadUrl: { type: 'string', format: 'uri' }, checksumSha256: { type: 'string', pattern: '^[a-f0-9]{64}$' }, releaseNotes: { type: 'string' } }, additionalProperties: false },
      DeviceCommandInput: { type: 'object', required: ['type', 'payload'], properties: { type: { type: 'string', enum: ['HAPTIC_THERAPY', 'DISPLAY_MESSAGE', 'SET_CONFIGURATION', 'RESTART'] }, payload: { type: 'object', additionalProperties: true }, idempotencyKey: { type: 'string' } }, additionalProperties: false },
      HeatmapContributionInput: { type: 'object', required: ['latitude', 'longitude', 'state'], properties: { latitude: { type: 'number' }, longitude: { type: 'number' }, state: { type: 'string' } }, additionalProperties: false },
      JournalInput: { type: 'object', required: ['content'], properties: { content: { type: 'string', maxLength: 10000 }, mood: { type: 'string' } }, additionalProperties: false },
      ImageUploadInput: { type: 'object', required: ['contentType', 'data'], properties: { contentType: { type: 'string', example: 'image/png' }, data: { type: 'string', format: 'byte' } }, additionalProperties: false },
      MindfulnessProgressInput: { type: 'object', required: ['activityId'], properties: { activityId: { type: 'string' }, completed: { type: 'boolean' }, progressSeconds: { type: 'integer', minimum: 0 } }, additionalProperties: false },
      MoodInput: { type: 'object', required: ['state', 'intensity'], properties: { state: { type: 'string' }, intensity: { type: 'integer', minimum: 1, maximum: 5 }, note: { type: 'string' }, triggers: { type: 'array', items: { type: 'string' } } }, additionalProperties: false },
      NotificationTokenInput: { type: 'object', required: ['token', 'platform'], properties: { token: { type: 'string' }, platform: { type: 'string' } }, additionalProperties: false },
      ProfileInput: { type: 'object', properties: { displayName: { type: 'string' }, birthDate: { type: 'string', format: 'date' }, timezone: { type: 'string' } }, additionalProperties: false },
      PsychologistApplicationInput: { type: 'object', required: ['licenseNumber'], properties: { licenseNumber: { type: 'string' }, specialization: { type: 'string' }, supportingDocumentUrl: { type: 'string', format: 'uri' } }, additionalProperties: false },
      ProviderInput: { type: 'object', required: ['name', 'type'], properties: { name: { type: 'string' }, type: { type: 'string' }, description: { type: 'string' }, contactUrl: { type: 'string', format: 'uri' } }, additionalProperties: false },
      ReferralInput: { type: 'object', required: ['providerId'], properties: { providerId: { type: 'string' }, reason: { type: 'string' }, note: { type: 'string' } }, additionalProperties: false },
      SimulatorDeviceInput: { type: 'object', required: ['serialNumber', 'model', 'claimSecret'], properties: { serialNumber: { type: 'string' }, model: { type: 'string' }, claimSecret: { type: 'string', writeOnly: true }, hardwareRevision: { type: 'string' }, bootloaderVersion: { type: 'string' }, protocolVersion: { type: 'string' }, supportedCommandTypes: { type: 'array', items: { type: 'string' } } }, additionalProperties: false },
    },
  },
};
